### ISSUE TITLE
Conduit: prometheus prefix should be configurable

### ISSUE THREAD

**Issue by winder** [algorand/indexer#1340]
The prometheus metrics currently use `indexer_daemon_` as a prefix. This should be a configurable option to the metrics.

```
metrics:
    mode: ON
    addr: ":9999"
    prefix: "conduit"
```
