### ISSUE TITLE
Invalid JSON written when using conduit file_writer

### ISSUE THREAD

**Issue by barnjamin** [algorand/indexer#1469]
### Subject of the issue

Using the conduit file_writer, JSON is produced with the integer value `0` as a key. This causes some programs to complain or fail altogether.

Conduit config:
```
hide-banner: true

log-level: "DEBUG"
log-file: "/tmp/conduit.log"

importer:
    name: algod
    config:
        netaddr: "http://localhost:4001"
        token: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

processors:
  - name: block_evaluator
    config:
        algod-addr: "http://localhost:4001"
        algod-token: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

exporter:
    name: file_writer 
    config: 
        block-dir: "/tmp/blocks"
        drop-certificate: true
```

![image](https://user-images.githubusercontent.com/520236/219380342-2ce02561-9a67-4d93-b906-b321b3403c69.png)
